value = [ "group55", 55 , 55.55 , 10 , "hello" , 7 ,0 , 10 , True , False ,]

print(value[0])
print(value[1])
print(value[2])


value[3] = 55.1
value[4] = "bye"
value[5] = 9.1


value += ["wwwe"]
value+= ["hi"]
value += ["ok"]
value +=  [5]
value += [8.9]

print(value)





# საკლასო 2 

number1=int(input("enter your first number: "))
number2=int(input("enter your second number: "))
number3=int(input("enter your third number: "))


user_number = [number1 , number2 , number3]





 













